version: '3.3'
services:
  SCP:
    # build: . # Build from Dockerfile
    container_name: scp
    image: hardliner66/scp
    network_mode: bridge
    environment:
      - TZ=Europe/Vienna
      - SERVERNAME=scpDocker
    volumes:
      - './server:/mnt/scp/server:rw'
      - './data:/mnt/scp/persistentdata:rw'
    ports:
      - '7777:7777/udp'
      - '27015:27015/udp'
